name: "Dev Deployment"

on:
    push: 
        branches: 
            - main
    workflow_dispatch: 

permissions:
    id-token: write
    contents: read

jobs:

    deploy:
        environment: dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - id: apply
              name: Validate and Apply
              env:
                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                BACKEND_RESOURCE_GROUP_NAME: rg-tf-storage
                BACKEND_STORAGE_ACCOUNT_NAME: satfdevproject
                BACKEND_STORAGE_CONTAINER_NAME: terraform
                TF_BACKEND_KEY: dev/terraform.tfstate
              working-directory: iaac/
              run: |
                terraform init \
                  -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
                  -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
                  -backend-config="container_name=$BACKEND_STORAGE_CONTAINER_NAME" \
                  -backend-config="key=$TF_BACKEND_KEY" \
                  -backend-config="use_oidc=true"

                terraform apply -var-file="parameters/dev.tfvars" -auto-approve

