name: Run Python Script

on:
    push:
        branches:
        - chore/git_demo  # Change to your default branch
    workflow_dispatch: 

env:
  TEST_USER: ${{ secrets.TEST_USER }}
  USER_VAR: ${{ vars.USER_VAR }}

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies if needed

      - name: Run script
        run: python main.py  # Replace with your Python script name